# Generated by Django 2.2 on 2019-04-16 03:50

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicles',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('estimated_price', models.IntegerField()),
                ('car_name', models.CharField(max_length=100)),
                ('miles', models.CharField(max_length=500)),
                ('vin', models.CharField(max_length=500)),
                ('body', models.CharField(max_length=500)),
                ('primary_damage', models.CharField(max_length=500)),
                ('secondary_damage', models.CharField(max_length=500)),
                ('start_code', models.CharField(max_length=500)),
                ('key_fob', models.CharField(max_length=500)),
                ('airbags', models.CharField(max_length=500)),
                ('car_image', models.CharField(max_length=500)),
                ('url', models.CharField(max_length=500)),
                ('value_est', models.FloatField()),
            ],
            options={
                'db_table': 'scrapy_items',
            },
        ),
    ]
